tests_complete_graph:
	ocamlbuild tests_complete_graph.native
	./tests_complete_graph.native

tests_mll_path:
	ocamlbuild tests_mll_path.native
	./tests_mll_path.native

all_tests: tests_complete_graph tests_mll_path